name: Static Analysis

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  commit-lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0
    - name: Check Commit Messages
      uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
      with:
        configFile: .commitlintrc.yml
  renovate-validation:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Validate Repository Renovate Config
      run: npx -y --package renovate -- renovate-config-validator renovate.json
